// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: core.proto

package server

import (
	"context"

	"core-service/core"
	"core-service/internal/logic/routingservice"
	"core-service/internal/svc"
)

type RoutingServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedRoutingServiceServer
}

func NewRoutingServiceServer(svcCtx *svc.ServiceContext) *RoutingServiceServer {
	return &RoutingServiceServer{
		svcCtx: svcCtx,
	}
}

// 路由决策（AI继续 or 转人工）
func (s *RoutingServiceServer) Route(ctx context.Context, in *core.RouteReq) (*core.RouteResp, error) {
	l := routingservicelogic.NewRouteLogic(ctx, s.svcCtx)
	return l.Route(in)
}

// 转人工客服
func (s *RoutingServiceServer) TransferToHuman(ctx context.Context, in *core.TransferToHumanReq) (*core.TransferToHumanResp, error) {
	l := routingservicelogic.NewTransferToHumanLogic(ctx, s.svcCtx)
	return l.TransferToHuman(in)
}

// 获取路由策略配置
func (s *RoutingServiceServer) GetRoutingStrategy(ctx context.Context, in *core.GetRoutingStrategyReq) (*core.GetRoutingStrategyResp, error) {
	l := routingservicelogic.NewGetRoutingStrategyLogic(ctx, s.svcCtx)
	return l.GetRoutingStrategy(in)
}
