// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: core.proto

package server

import (
	"context"

	"core-service/core"
	"core-service/internal/logic/ragservice"
	"core-service/internal/svc"
)

type RagServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedRagServiceServer
}

func NewRagServiceServer(svcCtx *svc.ServiceContext) *RagServiceServer {
	return &RagServiceServer{
		svcCtx: svcCtx,
	}
}

// 核心对话接口（检索+生成完整流程，90%场景使用）
func (s *RagServiceServer) Chat(ctx context.Context, in *core.ChatReq) (*core.ChatResp, error) {
	l := ragservicelogic.NewChatLogic(ctx, s.svcCtx)
	return l.Chat(in)
}

// 单独检索接口（仅检索不生成，用于智能提示、知识库测试等场景）
func (s *RagServiceServer) Search(ctx context.Context, in *core.SearchReq) (*core.SearchResp, error) {
	l := ragservicelogic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}
