// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: core.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagService_Chat_FullMethodName   = "/core.RagService/Chat"
	RagService_Search_FullMethodName = "/core.RagService/Search"
)

// RagServiceClient is the client API for RagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RagServiceClient interface {
	// 核心对话接口（检索+生成完整流程，90%场景使用）
	Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error)
	// 单独检索接口（仅检索不生成，用于智能提示、知识库测试等场景）
	Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
}

type ragServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagServiceClient(cc grpc.ClientConnInterface) RagServiceClient {
	return &ragServiceClient{cc}
}

func (c *ragServiceClient) Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResp)
	err := c.cc.Invoke(ctx, RagService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, RagService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServiceServer is the server API for RagService service.
// All implementations must embed UnimplementedRagServiceServer
// for forward compatibility.
type RagServiceServer interface {
	// 核心对话接口（检索+生成完整流程，90%场景使用）
	Chat(context.Context, *ChatReq) (*ChatResp, error)
	// 单独检索接口（仅检索不生成，用于智能提示、知识库测试等场景）
	Search(context.Context, *SearchReq) (*SearchResp, error)
	mustEmbedUnimplementedRagServiceServer()
}

// UnimplementedRagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServiceServer struct{}

func (UnimplementedRagServiceServer) Chat(context.Context, *ChatReq) (*ChatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedRagServiceServer) Search(context.Context, *SearchReq) (*SearchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRagServiceServer) mustEmbedUnimplementedRagServiceServer() {}
func (UnimplementedRagServiceServer) testEmbeddedByValue()                    {}

// UnsafeRagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServiceServer will
// result in compilation errors.
type UnsafeRagServiceServer interface {
	mustEmbedUnimplementedRagServiceServer()
}

func RegisterRagServiceServer(s grpc.ServiceRegistrar, srv RagServiceServer) {
	// If the following call pancis, it indicates UnimplementedRagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagService_ServiceDesc, srv)
}

func _RagService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).Chat(ctx, req.(*ChatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).Search(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RagService_ServiceDesc is the grpc.ServiceDesc for RagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.RagService",
	HandlerType: (*RagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Chat",
			Handler:    _RagService_Chat_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _RagService_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}

const (
	IntentService_DetectIntent_FullMethodName    = "/core.IntentService/DetectIntent"
	IntentService_ClassifyMessage_FullMethodName = "/core.IntentService/ClassifyMessage"
	IntentService_ExtractSlots_FullMethodName    = "/core.IntentService/ExtractSlots"
)

// IntentServiceClient is the client API for IntentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntentServiceClient interface {
	// 识别用户意图
	DetectIntent(ctx context.Context, in *DetectIntentReq, opts ...grpc.CallOption) (*DetectIntentResp, error)
	// 消息分类（快速分类：咨询/投诉/闲聊等）
	ClassifyMessage(ctx context.Context, in *ClassifyMessageReq, opts ...grpc.CallOption) (*ClassifyMessageResp, error)
	// 提取槽位信息（NER）
	ExtractSlots(ctx context.Context, in *ExtractSlotsReq, opts ...grpc.CallOption) (*ExtractSlotsResp, error)
}

type intentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntentServiceClient(cc grpc.ClientConnInterface) IntentServiceClient {
	return &intentServiceClient{cc}
}

func (c *intentServiceClient) DetectIntent(ctx context.Context, in *DetectIntentReq, opts ...grpc.CallOption) (*DetectIntentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectIntentResp)
	err := c.cc.Invoke(ctx, IntentService_DetectIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intentServiceClient) ClassifyMessage(ctx context.Context, in *ClassifyMessageReq, opts ...grpc.CallOption) (*ClassifyMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyMessageResp)
	err := c.cc.Invoke(ctx, IntentService_ClassifyMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intentServiceClient) ExtractSlots(ctx context.Context, in *ExtractSlotsReq, opts ...grpc.CallOption) (*ExtractSlotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractSlotsResp)
	err := c.cc.Invoke(ctx, IntentService_ExtractSlots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntentServiceServer is the server API for IntentService service.
// All implementations must embed UnimplementedIntentServiceServer
// for forward compatibility.
type IntentServiceServer interface {
	// 识别用户意图
	DetectIntent(context.Context, *DetectIntentReq) (*DetectIntentResp, error)
	// 消息分类（快速分类：咨询/投诉/闲聊等）
	ClassifyMessage(context.Context, *ClassifyMessageReq) (*ClassifyMessageResp, error)
	// 提取槽位信息（NER）
	ExtractSlots(context.Context, *ExtractSlotsReq) (*ExtractSlotsResp, error)
	mustEmbedUnimplementedIntentServiceServer()
}

// UnimplementedIntentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntentServiceServer struct{}

func (UnimplementedIntentServiceServer) DetectIntent(context.Context, *DetectIntentReq) (*DetectIntentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectIntent not implemented")
}
func (UnimplementedIntentServiceServer) ClassifyMessage(context.Context, *ClassifyMessageReq) (*ClassifyMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyMessage not implemented")
}
func (UnimplementedIntentServiceServer) ExtractSlots(context.Context, *ExtractSlotsReq) (*ExtractSlotsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtractSlots not implemented")
}
func (UnimplementedIntentServiceServer) mustEmbedUnimplementedIntentServiceServer() {}
func (UnimplementedIntentServiceServer) testEmbeddedByValue()                       {}

// UnsafeIntentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntentServiceServer will
// result in compilation errors.
type UnsafeIntentServiceServer interface {
	mustEmbedUnimplementedIntentServiceServer()
}

func RegisterIntentServiceServer(s grpc.ServiceRegistrar, srv IntentServiceServer) {
	// If the following call pancis, it indicates UnimplementedIntentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntentService_ServiceDesc, srv)
}

func _IntentService_DetectIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectIntentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentServiceServer).DetectIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentService_DetectIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentServiceServer).DetectIntent(ctx, req.(*DetectIntentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntentService_ClassifyMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentServiceServer).ClassifyMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentService_ClassifyMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentServiceServer).ClassifyMessage(ctx, req.(*ClassifyMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntentService_ExtractSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractSlotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentServiceServer).ExtractSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentService_ExtractSlots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentServiceServer).ExtractSlots(ctx, req.(*ExtractSlotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IntentService_ServiceDesc is the grpc.ServiceDesc for IntentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.IntentService",
	HandlerType: (*IntentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectIntent",
			Handler:    _IntentService_DetectIntent_Handler,
		},
		{
			MethodName: "ClassifyMessage",
			Handler:    _IntentService_ClassifyMessage_Handler,
		},
		{
			MethodName: "ExtractSlots",
			Handler:    _IntentService_ExtractSlots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}

const (
	EmotionService_AnalyzeEmotion_FullMethodName    = "/core.EmotionService/AnalyzeEmotion"
	EmotionService_DetectRisk_FullMethodName        = "/core.EmotionService/DetectRisk"
	EmotionService_ContentModeration_FullMethodName = "/core.EmotionService/ContentModeration"
)

// EmotionServiceClient is the client API for EmotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmotionServiceClient interface {
	// 分析用户情绪
	AnalyzeEmotion(ctx context.Context, in *AnalyzeEmotionReq, opts ...grpc.CallOption) (*AnalyzeEmotionResp, error)
	// 风险预警检测（检测高危用户）
	DetectRisk(ctx context.Context, in *DetectRiskReq, opts ...grpc.CallOption) (*DetectRiskResp, error)
	// 内容合规审核（支持双向审核：用户输入 + AI输出）
	ContentModeration(ctx context.Context, in *ContentModerationReq, opts ...grpc.CallOption) (*ContentModerationResp, error)
}

type emotionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmotionServiceClient(cc grpc.ClientConnInterface) EmotionServiceClient {
	return &emotionServiceClient{cc}
}

func (c *emotionServiceClient) AnalyzeEmotion(ctx context.Context, in *AnalyzeEmotionReq, opts ...grpc.CallOption) (*AnalyzeEmotionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeEmotionResp)
	err := c.cc.Invoke(ctx, EmotionService_AnalyzeEmotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionServiceClient) DetectRisk(ctx context.Context, in *DetectRiskReq, opts ...grpc.CallOption) (*DetectRiskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectRiskResp)
	err := c.cc.Invoke(ctx, EmotionService_DetectRisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionServiceClient) ContentModeration(ctx context.Context, in *ContentModerationReq, opts ...grpc.CallOption) (*ContentModerationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentModerationResp)
	err := c.cc.Invoke(ctx, EmotionService_ContentModeration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmotionServiceServer is the server API for EmotionService service.
// All implementations must embed UnimplementedEmotionServiceServer
// for forward compatibility.
type EmotionServiceServer interface {
	// 分析用户情绪
	AnalyzeEmotion(context.Context, *AnalyzeEmotionReq) (*AnalyzeEmotionResp, error)
	// 风险预警检测（检测高危用户）
	DetectRisk(context.Context, *DetectRiskReq) (*DetectRiskResp, error)
	// 内容合规审核（支持双向审核：用户输入 + AI输出）
	ContentModeration(context.Context, *ContentModerationReq) (*ContentModerationResp, error)
	mustEmbedUnimplementedEmotionServiceServer()
}

// UnimplementedEmotionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmotionServiceServer struct{}

func (UnimplementedEmotionServiceServer) AnalyzeEmotion(context.Context, *AnalyzeEmotionReq) (*AnalyzeEmotionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeEmotion not implemented")
}
func (UnimplementedEmotionServiceServer) DetectRisk(context.Context, *DetectRiskReq) (*DetectRiskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectRisk not implemented")
}
func (UnimplementedEmotionServiceServer) ContentModeration(context.Context, *ContentModerationReq) (*ContentModerationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContentModeration not implemented")
}
func (UnimplementedEmotionServiceServer) mustEmbedUnimplementedEmotionServiceServer() {}
func (UnimplementedEmotionServiceServer) testEmbeddedByValue()                        {}

// UnsafeEmotionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmotionServiceServer will
// result in compilation errors.
type UnsafeEmotionServiceServer interface {
	mustEmbedUnimplementedEmotionServiceServer()
}

func RegisterEmotionServiceServer(s grpc.ServiceRegistrar, srv EmotionServiceServer) {
	// If the following call pancis, it indicates UnimplementedEmotionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmotionService_ServiceDesc, srv)
}

func _EmotionService_AnalyzeEmotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeEmotionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionServiceServer).AnalyzeEmotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionService_AnalyzeEmotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionServiceServer).AnalyzeEmotion(ctx, req.(*AnalyzeEmotionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionService_DetectRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRiskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionServiceServer).DetectRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionService_DetectRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionServiceServer).DetectRisk(ctx, req.(*DetectRiskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionService_ContentModeration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentModerationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionServiceServer).ContentModeration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionService_ContentModeration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionServiceServer).ContentModeration(ctx, req.(*ContentModerationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EmotionService_ServiceDesc is the grpc.ServiceDesc for EmotionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmotionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.EmotionService",
	HandlerType: (*EmotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeEmotion",
			Handler:    _EmotionService_AnalyzeEmotion_Handler,
		},
		{
			MethodName: "DetectRisk",
			Handler:    _EmotionService_DetectRisk_Handler,
		},
		{
			MethodName: "ContentModeration",
			Handler:    _EmotionService_ContentModeration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}

const (
	RoutingService_Route_FullMethodName              = "/core.RoutingService/Route"
	RoutingService_TransferToHuman_FullMethodName    = "/core.RoutingService/TransferToHuman"
	RoutingService_GetRoutingStrategy_FullMethodName = "/core.RoutingService/GetRoutingStrategy"
)

// RoutingServiceClient is the client API for RoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoutingServiceClient interface {
	// 路由决策（AI继续 or 转人工）
	Route(ctx context.Context, in *RouteReq, opts ...grpc.CallOption) (*RouteResp, error)
	// 转人工客服
	TransferToHuman(ctx context.Context, in *TransferToHumanReq, opts ...grpc.CallOption) (*TransferToHumanResp, error)
	// 获取路由策略配置
	GetRoutingStrategy(ctx context.Context, in *GetRoutingStrategyReq, opts ...grpc.CallOption) (*GetRoutingStrategyResp, error)
}

type routingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingServiceClient(cc grpc.ClientConnInterface) RoutingServiceClient {
	return &routingServiceClient{cc}
}

func (c *routingServiceClient) Route(ctx context.Context, in *RouteReq, opts ...grpc.CallOption) (*RouteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResp)
	err := c.cc.Invoke(ctx, RoutingService_Route_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) TransferToHuman(ctx context.Context, in *TransferToHumanReq, opts ...grpc.CallOption) (*TransferToHumanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferToHumanResp)
	err := c.cc.Invoke(ctx, RoutingService_TransferToHuman_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) GetRoutingStrategy(ctx context.Context, in *GetRoutingStrategyReq, opts ...grpc.CallOption) (*GetRoutingStrategyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingStrategyResp)
	err := c.cc.Invoke(ctx, RoutingService_GetRoutingStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServiceServer is the server API for RoutingService service.
// All implementations must embed UnimplementedRoutingServiceServer
// for forward compatibility.
type RoutingServiceServer interface {
	// 路由决策（AI继续 or 转人工）
	Route(context.Context, *RouteReq) (*RouteResp, error)
	// 转人工客服
	TransferToHuman(context.Context, *TransferToHumanReq) (*TransferToHumanResp, error)
	// 获取路由策略配置
	GetRoutingStrategy(context.Context, *GetRoutingStrategyReq) (*GetRoutingStrategyResp, error)
	mustEmbedUnimplementedRoutingServiceServer()
}

// UnimplementedRoutingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServiceServer struct{}

func (UnimplementedRoutingServiceServer) Route(context.Context, *RouteReq) (*RouteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedRoutingServiceServer) TransferToHuman(context.Context, *TransferToHumanReq) (*TransferToHumanResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferToHuman not implemented")
}
func (UnimplementedRoutingServiceServer) GetRoutingStrategy(context.Context, *GetRoutingStrategyReq) (*GetRoutingStrategyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingStrategy not implemented")
}
func (UnimplementedRoutingServiceServer) mustEmbedUnimplementedRoutingServiceServer() {}
func (UnimplementedRoutingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServiceServer will
// result in compilation errors.
type UnsafeRoutingServiceServer interface {
	mustEmbedUnimplementedRoutingServiceServer()
}

func RegisterRoutingServiceServer(s grpc.ServiceRegistrar, srv RoutingServiceServer) {
	// If the following call pancis, it indicates UnimplementedRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutingService_ServiceDesc, srv)
}

func _RoutingService_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_Route_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).Route(ctx, req.(*RouteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_TransferToHuman_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferToHumanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).TransferToHuman(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_TransferToHuman_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).TransferToHuman(ctx, req.(*TransferToHumanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_GetRoutingStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingStrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetRoutingStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetRoutingStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetRoutingStrategy(ctx, req.(*GetRoutingStrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutingService_ServiceDesc is the grpc.ServiceDesc for RoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.RoutingService",
	HandlerType: (*RoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Route",
			Handler:    _RoutingService_Route_Handler,
		},
		{
			MethodName: "TransferToHuman",
			Handler:    _RoutingService_TransferToHuman_Handler,
		},
		{
			MethodName: "GetRoutingStrategy",
			Handler:    _RoutingService_GetRoutingStrategy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}

const (
	PromptService_GetTemplate_FullMethodName    = "/core.PromptService/GetTemplate"
	PromptService_ListTemplates_FullMethodName  = "/core.PromptService/ListTemplates"
	PromptService_CreateTemplate_FullMethodName = "/core.PromptService/CreateTemplate"
	PromptService_UpdateTemplate_FullMethodName = "/core.PromptService/UpdateTemplate"
	PromptService_DeleteTemplate_FullMethodName = "/core.PromptService/DeleteTemplate"
	PromptService_RenderTemplate_FullMethodName = "/core.PromptService/RenderTemplate"
)

// PromptServiceClient is the client API for PromptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromptServiceClient interface {
	// 获取单个模板
	GetTemplate(ctx context.Context, in *GetTemplateReq, opts ...grpc.CallOption) (*GetTemplateResp, error)
	// 获取模板列表
	ListTemplates(ctx context.Context, in *ListTemplatesReq, opts ...grpc.CallOption) (*ListTemplatesResp, error)
	// 创建模板
	CreateTemplate(ctx context.Context, in *CreateTemplateReq, opts ...grpc.CallOption) (*CreateTemplateResp, error)
	// 更新模板
	UpdateTemplate(ctx context.Context, in *UpdateTemplateReq, opts ...grpc.CallOption) (*UpdateTemplateResp, error)
	// 删除模板
	DeleteTemplate(ctx context.Context, in *DeleteTemplateReq, opts ...grpc.CallOption) (*DeleteTemplateResp, error)
	// 渲染模板（填充变量）
	RenderTemplate(ctx context.Context, in *RenderTemplateReq, opts ...grpc.CallOption) (*RenderTemplateResp, error)
}

type promptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromptServiceClient(cc grpc.ClientConnInterface) PromptServiceClient {
	return &promptServiceClient{cc}
}

func (c *promptServiceClient) GetTemplate(ctx context.Context, in *GetTemplateReq, opts ...grpc.CallOption) (*GetTemplateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTemplateResp)
	err := c.cc.Invoke(ctx, PromptService_GetTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promptServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesReq, opts ...grpc.CallOption) (*ListTemplatesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResp)
	err := c.cc.Invoke(ctx, PromptService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promptServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateReq, opts ...grpc.CallOption) (*CreateTemplateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTemplateResp)
	err := c.cc.Invoke(ctx, PromptService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promptServiceClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateReq, opts ...grpc.CallOption) (*UpdateTemplateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTemplateResp)
	err := c.cc.Invoke(ctx, PromptService_UpdateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promptServiceClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateReq, opts ...grpc.CallOption) (*DeleteTemplateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTemplateResp)
	err := c.cc.Invoke(ctx, PromptService_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promptServiceClient) RenderTemplate(ctx context.Context, in *RenderTemplateReq, opts ...grpc.CallOption) (*RenderTemplateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderTemplateResp)
	err := c.cc.Invoke(ctx, PromptService_RenderTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromptServiceServer is the server API for PromptService service.
// All implementations must embed UnimplementedPromptServiceServer
// for forward compatibility.
type PromptServiceServer interface {
	// 获取单个模板
	GetTemplate(context.Context, *GetTemplateReq) (*GetTemplateResp, error)
	// 获取模板列表
	ListTemplates(context.Context, *ListTemplatesReq) (*ListTemplatesResp, error)
	// 创建模板
	CreateTemplate(context.Context, *CreateTemplateReq) (*CreateTemplateResp, error)
	// 更新模板
	UpdateTemplate(context.Context, *UpdateTemplateReq) (*UpdateTemplateResp, error)
	// 删除模板
	DeleteTemplate(context.Context, *DeleteTemplateReq) (*DeleteTemplateResp, error)
	// 渲染模板（填充变量）
	RenderTemplate(context.Context, *RenderTemplateReq) (*RenderTemplateResp, error)
	mustEmbedUnimplementedPromptServiceServer()
}

// UnimplementedPromptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromptServiceServer struct{}

func (UnimplementedPromptServiceServer) GetTemplate(context.Context, *GetTemplateReq) (*GetTemplateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTemplate not implemented")
}
func (UnimplementedPromptServiceServer) ListTemplates(context.Context, *ListTemplatesReq) (*ListTemplatesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedPromptServiceServer) CreateTemplate(context.Context, *CreateTemplateReq) (*CreateTemplateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedPromptServiceServer) UpdateTemplate(context.Context, *UpdateTemplateReq) (*UpdateTemplateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedPromptServiceServer) DeleteTemplate(context.Context, *DeleteTemplateReq) (*DeleteTemplateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedPromptServiceServer) RenderTemplate(context.Context, *RenderTemplateReq) (*RenderTemplateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderTemplate not implemented")
}
func (UnimplementedPromptServiceServer) mustEmbedUnimplementedPromptServiceServer() {}
func (UnimplementedPromptServiceServer) testEmbeddedByValue()                       {}

// UnsafePromptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromptServiceServer will
// result in compilation errors.
type UnsafePromptServiceServer interface {
	mustEmbedUnimplementedPromptServiceServer()
}

func RegisterPromptServiceServer(s grpc.ServiceRegistrar, srv PromptServiceServer) {
	// If the following call pancis, it indicates UnimplementedPromptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromptService_ServiceDesc, srv)
}

func _PromptService_GetTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).GetTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_GetTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).GetTemplate(ctx, req.(*GetTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromptService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).ListTemplates(ctx, req.(*ListTemplatesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromptService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).CreateTemplate(ctx, req.(*CreateTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromptService_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).UpdateTemplate(ctx, req.(*UpdateTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromptService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).DeleteTemplate(ctx, req.(*DeleteTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromptService_RenderTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).RenderTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_RenderTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).RenderTemplate(ctx, req.(*RenderTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PromptService_ServiceDesc is the grpc.ServiceDesc for PromptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.PromptService",
	HandlerType: (*PromptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTemplate",
			Handler:    _PromptService_GetTemplate_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _PromptService_ListTemplates_Handler,
		},
		{
			MethodName: "CreateTemplate",
			Handler:    _PromptService_CreateTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _PromptService_UpdateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _PromptService_DeleteTemplate_Handler,
		},
		{
			MethodName: "RenderTemplate",
			Handler:    _PromptService_RenderTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core.proto",
}
