// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: core.proto

package server

import (
	"context"

	"core-service/core"
	"core-service/internal/logic/emotionservice"
	"core-service/internal/svc"
)

type EmotionServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedEmotionServiceServer
}

func NewEmotionServiceServer(svcCtx *svc.ServiceContext) *EmotionServiceServer {
	return &EmotionServiceServer{
		svcCtx: svcCtx,
	}
}

// 分析用户情绪
func (s *EmotionServiceServer) AnalyzeEmotion(ctx context.Context, in *core.AnalyzeEmotionReq) (*core.AnalyzeEmotionResp, error) {
	l := emotionservicelogic.NewAnalyzeEmotionLogic(ctx, s.svcCtx)
	return l.AnalyzeEmotion(in)
}

// 风险预警检测（检测高危用户）
func (s *EmotionServiceServer) DetectRisk(ctx context.Context, in *core.DetectRiskReq) (*core.DetectRiskResp, error) {
	l := emotionservicelogic.NewDetectRiskLogic(ctx, s.svcCtx)
	return l.DetectRisk(in)
}

// 内容合规审核（支持双向审核：用户输入 + AI输出）
func (s *EmotionServiceServer) ContentModeration(ctx context.Context, in *core.ContentModerationReq) (*core.ContentModerationResp, error) {
	l := emotionservicelogic.NewContentModerationLogic(ctx, s.svcCtx)
	return l.ContentModeration(in)
}
