// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: data.proto

package analyticsservice

import (
	"context"

	"data-service/data"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Chunk                    = data.Chunk
	CreateDocumentReq        = data.CreateDocumentReq
	CreateDocumentResp       = data.CreateDocumentResp
	CreateKnowledgeBaseReq   = data.CreateKnowledgeBaseReq
	CreateKnowledgeBaseResp  = data.CreateKnowledgeBaseResp
	DeleteChunksReq          = data.DeleteChunksReq
	DeleteChunksResp         = data.DeleteChunksResp
	DeleteDocumentReq        = data.DeleteDocumentReq
	DeleteDocumentResp       = data.DeleteDocumentResp
	DeleteKnowledgeBaseReq   = data.DeleteKnowledgeBaseReq
	DeleteKnowledgeBaseResp  = data.DeleteKnowledgeBaseResp
	Document                 = data.Document
	GetDocumentReq           = data.GetDocumentReq
	GetDocumentResp          = data.GetDocumentResp
	GetKnowledgeBaseReq      = data.GetKnowledgeBaseReq
	GetKnowledgeBaseResp     = data.GetKnowledgeBaseResp
	KnowledgeBase            = data.KnowledgeBase
	ListDocumentsReq         = data.ListDocumentsReq
	ListDocumentsResp        = data.ListDocumentsResp
	ListKnowledgeBasesReq    = data.ListKnowledgeBasesReq
	ListKnowledgeBasesResp   = data.ListKnowledgeBasesResp
	SaveChunksReq            = data.SaveChunksReq
	SaveChunksResp           = data.SaveChunksResp
	UpdateDocumentStatusReq  = data.UpdateDocumentStatusReq
	UpdateDocumentStatusResp = data.UpdateDocumentStatusResp

	AnalyticsService interface {
	}

	defaultAnalyticsService struct {
		cli zrpc.Client
	}
)

func NewAnalyticsService(cli zrpc.Client) AnalyticsService {
	return &defaultAnalyticsService{
		cli: cli,
	}
}
