// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: data.proto

package knowledgeservice

import (
	"context"

	"data-service/data"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Chunk                    = data.Chunk
	CreateDocumentReq        = data.CreateDocumentReq
	CreateDocumentResp       = data.CreateDocumentResp
	CreateKnowledgeBaseReq   = data.CreateKnowledgeBaseReq
	CreateKnowledgeBaseResp  = data.CreateKnowledgeBaseResp
	DeleteChunksReq          = data.DeleteChunksReq
	DeleteChunksResp         = data.DeleteChunksResp
	DeleteDocumentReq        = data.DeleteDocumentReq
	DeleteDocumentResp       = data.DeleteDocumentResp
	DeleteKnowledgeBaseReq   = data.DeleteKnowledgeBaseReq
	DeleteKnowledgeBaseResp  = data.DeleteKnowledgeBaseResp
	Document                 = data.Document
	GetDocumentReq           = data.GetDocumentReq
	GetDocumentResp          = data.GetDocumentResp
	GetKnowledgeBaseReq      = data.GetKnowledgeBaseReq
	GetKnowledgeBaseResp     = data.GetKnowledgeBaseResp
	KnowledgeBase            = data.KnowledgeBase
	ListDocumentsReq         = data.ListDocumentsReq
	ListDocumentsResp        = data.ListDocumentsResp
	ListKnowledgeBasesReq    = data.ListKnowledgeBasesReq
	ListKnowledgeBasesResp   = data.ListKnowledgeBasesResp
	SaveChunksReq            = data.SaveChunksReq
	SaveChunksResp           = data.SaveChunksResp
	UpdateDocumentStatusReq  = data.UpdateDocumentStatusReq
	UpdateDocumentStatusResp = data.UpdateDocumentStatusResp

	KnowledgeService interface {
		CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseReq, opts ...grpc.CallOption) (*CreateKnowledgeBaseResp, error)
		ListKnowledgeBases(ctx context.Context, in *ListKnowledgeBasesReq, opts ...grpc.CallOption) (*ListKnowledgeBasesResp, error)
		GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseReq, opts ...grpc.CallOption) (*GetKnowledgeBaseResp, error)
		DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseReq, opts ...grpc.CallOption) (*DeleteKnowledgeBaseResp, error)
	}

	defaultKnowledgeService struct {
		cli zrpc.Client
	}
)

func NewKnowledgeService(cli zrpc.Client) KnowledgeService {
	return &defaultKnowledgeService{
		cli: cli,
	}
}

func (m *defaultKnowledgeService) CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseReq, opts ...grpc.CallOption) (*CreateKnowledgeBaseResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.CreateKnowledgeBase(ctx, in, opts...)
}

func (m *defaultKnowledgeService) ListKnowledgeBases(ctx context.Context, in *ListKnowledgeBasesReq, opts ...grpc.CallOption) (*ListKnowledgeBasesResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.ListKnowledgeBases(ctx, in, opts...)
}

func (m *defaultKnowledgeService) GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseReq, opts ...grpc.CallOption) (*GetKnowledgeBaseResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.GetKnowledgeBase(ctx, in, opts...)
}

func (m *defaultKnowledgeService) DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseReq, opts ...grpc.CallOption) (*DeleteKnowledgeBaseResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.DeleteKnowledgeBase(ctx, in, opts...)
}
