// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: data.proto

package knowledgeservice

import (
	"context"

	"data-service/data"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Chunk                    = data.Chunk
	CreateDocumentReq        = data.CreateDocumentReq
	CreateDocumentResp       = data.CreateDocumentResp
	CreateKnowledgeBaseReq   = data.CreateKnowledgeBaseReq
	CreateKnowledgeBaseResp  = data.CreateKnowledgeBaseResp
	DeleteChunksReq          = data.DeleteChunksReq
	DeleteChunksResp         = data.DeleteChunksResp
	DeleteDocumentReq        = data.DeleteDocumentReq
	DeleteDocumentResp       = data.DeleteDocumentResp
	DeleteKnowledgeBaseReq   = data.DeleteKnowledgeBaseReq
	DeleteKnowledgeBaseResp  = data.DeleteKnowledgeBaseResp
	Document                 = data.Document
	GetDocumentReq           = data.GetDocumentReq
	GetDocumentResp          = data.GetDocumentResp
	GetKnowledgeBaseReq      = data.GetKnowledgeBaseReq
	GetKnowledgeBaseResp     = data.GetKnowledgeBaseResp
	KnowledgeBase            = data.KnowledgeBase
	ListDocumentsReq         = data.ListDocumentsReq
	ListDocumentsResp        = data.ListDocumentsResp
	ListKnowledgeBasesReq    = data.ListKnowledgeBasesReq
	ListKnowledgeBasesResp   = data.ListKnowledgeBasesResp
	SaveChunksReq            = data.SaveChunksReq
	SaveChunksResp           = data.SaveChunksResp
	UpdateDocumentStatusReq  = data.UpdateDocumentStatusReq
	UpdateDocumentStatusResp = data.UpdateDocumentStatusResp
	UpdateKnowledgeBaseReq   = data.UpdateKnowledgeBaseReq
	UpdateKnowledgeBaseResp  = data.UpdateKnowledgeBaseResp

	KnowledgeService interface {
		CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseReq, opts ...grpc.CallOption) (*CreateKnowledgeBaseResp, error)
		ListKnowledgeBases(ctx context.Context, in *ListKnowledgeBasesReq, opts ...grpc.CallOption) (*ListKnowledgeBasesResp, error)
		GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseReq, opts ...grpc.CallOption) (*GetKnowledgeBaseResp, error)
		UpdateKnowledgeBase(ctx context.Context, in *UpdateKnowledgeBaseReq, opts ...grpc.CallOption) (*UpdateKnowledgeBaseResp, error)
		DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseReq, opts ...grpc.CallOption) (*DeleteKnowledgeBaseResp, error)
		CreateDocument(ctx context.Context, in *CreateDocumentReq, opts ...grpc.CallOption) (*CreateDocumentResp, error)
		ListDocuments(ctx context.Context, in *ListDocumentsReq, opts ...grpc.CallOption) (*ListDocumentsResp, error)
		GetDocument(ctx context.Context, in *GetDocumentReq, opts ...grpc.CallOption) (*GetDocumentResp, error)
		UpdateDocumentStatus(ctx context.Context, in *UpdateDocumentStatusReq, opts ...grpc.CallOption) (*UpdateDocumentStatusResp, error)
		DeleteDocument(ctx context.Context, in *DeleteDocumentReq, opts ...grpc.CallOption) (*DeleteDocumentResp, error)
	}

	defaultKnowledgeService struct {
		cli zrpc.Client
	}
)

func NewKnowledgeService(cli zrpc.Client) KnowledgeService {
	return &defaultKnowledgeService{
		cli: cli,
	}
}

func (m *defaultKnowledgeService) CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseReq, opts ...grpc.CallOption) (*CreateKnowledgeBaseResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.CreateKnowledgeBase(ctx, in, opts...)
}

func (m *defaultKnowledgeService) ListKnowledgeBases(ctx context.Context, in *ListKnowledgeBasesReq, opts ...grpc.CallOption) (*ListKnowledgeBasesResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.ListKnowledgeBases(ctx, in, opts...)
}

func (m *defaultKnowledgeService) GetKnowledgeBase(ctx context.Context, in *GetKnowledgeBaseReq, opts ...grpc.CallOption) (*GetKnowledgeBaseResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.GetKnowledgeBase(ctx, in, opts...)
}

func (m *defaultKnowledgeService) UpdateKnowledgeBase(ctx context.Context, in *UpdateKnowledgeBaseReq, opts ...grpc.CallOption) (*UpdateKnowledgeBaseResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.UpdateKnowledgeBase(ctx, in, opts...)
}

func (m *defaultKnowledgeService) DeleteKnowledgeBase(ctx context.Context, in *DeleteKnowledgeBaseReq, opts ...grpc.CallOption) (*DeleteKnowledgeBaseResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.DeleteKnowledgeBase(ctx, in, opts...)
}

func (m *defaultKnowledgeService) CreateDocument(ctx context.Context, in *CreateDocumentReq, opts ...grpc.CallOption) (*CreateDocumentResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.CreateDocument(ctx, in, opts...)
}

func (m *defaultKnowledgeService) ListDocuments(ctx context.Context, in *ListDocumentsReq, opts ...grpc.CallOption) (*ListDocumentsResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.ListDocuments(ctx, in, opts...)
}

func (m *defaultKnowledgeService) GetDocument(ctx context.Context, in *GetDocumentReq, opts ...grpc.CallOption) (*GetDocumentResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.GetDocument(ctx, in, opts...)
}

func (m *defaultKnowledgeService) UpdateDocumentStatus(ctx context.Context, in *UpdateDocumentStatusReq, opts ...grpc.CallOption) (*UpdateDocumentStatusResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.UpdateDocumentStatus(ctx, in, opts...)
}

func (m *defaultKnowledgeService) DeleteDocument(ctx context.Context, in *DeleteDocumentReq, opts ...grpc.CallOption) (*DeleteDocumentResp, error) {
	client := data.NewKnowledgeServiceClient(m.cli.Conn())
	return client.DeleteDocument(ctx, in, opts...)
}
