// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: core.proto

package ragservice

import (
	"context"

	"core-service/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalyzeEmotionReq      = core.AnalyzeEmotionReq
	AnalyzeEmotionResp     = core.AnalyzeEmotionResp
	ChatReq                = core.ChatReq
	ChatResp               = core.ChatResp
	ClassifyMessageReq     = core.ClassifyMessageReq
	ClassifyMessageResp    = core.ClassifyMessageResp
	ContentModerationReq   = core.ContentModerationReq
	ContentModerationResp  = core.ContentModerationResp
	CreateTemplateReq      = core.CreateTemplateReq
	CreateTemplateResp     = core.CreateTemplateResp
	DeleteTemplateReq      = core.DeleteTemplateReq
	DeleteTemplateResp     = core.DeleteTemplateResp
	DetectIntentReq        = core.DetectIntentReq
	DetectIntentResp       = core.DetectIntentResp
	DetectRiskReq          = core.DetectRiskReq
	DetectRiskResp         = core.DetectRiskResp
	ExtractSlotsReq        = core.ExtractSlotsReq
	ExtractSlotsResp       = core.ExtractSlotsResp
	GetRoutingStrategyReq  = core.GetRoutingStrategyReq
	GetRoutingStrategyResp = core.GetRoutingStrategyResp
	GetTemplateReq         = core.GetTemplateReq
	GetTemplateResp        = core.GetTemplateResp
	ListTemplatesReq       = core.ListTemplatesReq
	ListTemplatesResp      = core.ListTemplatesResp
	RenderTemplateReq      = core.RenderTemplateReq
	RenderTemplateResp     = core.RenderTemplateResp
	RouteReq               = core.RouteReq
	RouteResp              = core.RouteResp
	SearchReq              = core.SearchReq
	SearchResp             = core.SearchResp
	TransferToHumanReq     = core.TransferToHumanReq
	TransferToHumanResp    = core.TransferToHumanResp
	UpdateTemplateReq      = core.UpdateTemplateReq
	UpdateTemplateResp     = core.UpdateTemplateResp

	RagService interface {
		// 核心对话接口（检索+生成完整流程，90%场景使用）
		Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error)
		// 单独检索接口（仅检索不生成，用于智能提示、知识库测试等场景）
		Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
	}

	defaultRagService struct {
		cli zrpc.Client
	}
)

func NewRagService(cli zrpc.Client) RagService {
	return &defaultRagService{
		cli: cli,
	}
}

// 核心对话接口（检索+生成完整流程，90%场景使用）
func (m *defaultRagService) Chat(ctx context.Context, in *ChatReq, opts ...grpc.CallOption) (*ChatResp, error) {
	client := core.NewRagServiceClient(m.cli.Conn())
	return client.Chat(ctx, in, opts...)
}

// 单独检索接口（仅检索不生成，用于智能提示、知识库测试等场景）
func (m *defaultRagService) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	client := core.NewRagServiceClient(m.cli.Conn())
	return client.Search(ctx, in, opts...)
}
