services:
  mongodb:
    hostname: mongodb
    image: mongodb/mongodb-atlas-local
#    environment:
#      - MONGODB_INITDB_ROOT_USERNAME=user
#      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27030:27017"
    volumes:
      - data:/data/db
      - config:/data/configdb
volumes:
  data:
  config: