// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: core.proto

package routingservice

import (
	"context"

	"core-service/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalyzeEmotionReq      = core.AnalyzeEmotionReq
	AnalyzeEmotionResp     = core.AnalyzeEmotionResp
	ChatReq                = core.ChatReq
	ChatResp               = core.ChatResp
	ClassifyMessageReq     = core.ClassifyMessageReq
	ClassifyMessageResp    = core.ClassifyMessageResp
	ContentModerationReq   = core.ContentModerationReq
	ContentModerationResp  = core.ContentModerationResp
	CreateTemplateReq      = core.CreateTemplateReq
	CreateTemplateResp     = core.CreateTemplateResp
	DeleteTemplateReq      = core.DeleteTemplateReq
	DeleteTemplateResp     = core.DeleteTemplateResp
	DetectIntentReq        = core.DetectIntentReq
	DetectIntentResp       = core.DetectIntentResp
	DetectRiskReq          = core.DetectRiskReq
	DetectRiskResp         = core.DetectRiskResp
	ExtractSlotsReq        = core.ExtractSlotsReq
	ExtractSlotsResp       = core.ExtractSlotsResp
	GetRoutingStrategyReq  = core.GetRoutingStrategyReq
	GetRoutingStrategyResp = core.GetRoutingStrategyResp
	GetTemplateReq         = core.GetTemplateReq
	GetTemplateResp        = core.GetTemplateResp
	ListTemplatesReq       = core.ListTemplatesReq
	ListTemplatesResp      = core.ListTemplatesResp
	RenderTemplateReq      = core.RenderTemplateReq
	RenderTemplateResp     = core.RenderTemplateResp
	RouteReq               = core.RouteReq
	RouteResp              = core.RouteResp
	SearchReq              = core.SearchReq
	SearchResp             = core.SearchResp
	TransferToHumanReq     = core.TransferToHumanReq
	TransferToHumanResp    = core.TransferToHumanResp
	UpdateTemplateReq      = core.UpdateTemplateReq
	UpdateTemplateResp     = core.UpdateTemplateResp

	RoutingService interface {
		// 路由决策（AI继续 or 转人工）
		Route(ctx context.Context, in *RouteReq, opts ...grpc.CallOption) (*RouteResp, error)
		// 转人工客服
		TransferToHuman(ctx context.Context, in *TransferToHumanReq, opts ...grpc.CallOption) (*TransferToHumanResp, error)
		// 获取路由策略配置
		GetRoutingStrategy(ctx context.Context, in *GetRoutingStrategyReq, opts ...grpc.CallOption) (*GetRoutingStrategyResp, error)
	}

	defaultRoutingService struct {
		cli zrpc.Client
	}
)

func NewRoutingService(cli zrpc.Client) RoutingService {
	return &defaultRoutingService{
		cli: cli,
	}
}

// 路由决策（AI继续 or 转人工）
func (m *defaultRoutingService) Route(ctx context.Context, in *RouteReq, opts ...grpc.CallOption) (*RouteResp, error) {
	client := core.NewRoutingServiceClient(m.cli.Conn())
	return client.Route(ctx, in, opts...)
}

// 转人工客服
func (m *defaultRoutingService) TransferToHuman(ctx context.Context, in *TransferToHumanReq, opts ...grpc.CallOption) (*TransferToHumanResp, error) {
	client := core.NewRoutingServiceClient(m.cli.Conn())
	return client.TransferToHuman(ctx, in, opts...)
}

// 获取路由策略配置
func (m *defaultRoutingService) GetRoutingStrategy(ctx context.Context, in *GetRoutingStrategyReq, opts ...grpc.CallOption) (*GetRoutingStrategyResp, error) {
	client := core.NewRoutingServiceClient(m.cli.Conn())
	return client.GetRoutingStrategy(ctx, in, opts...)
}
