// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: core.proto

package promptservice

import (
	"context"

	"core-service/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalyzeEmotionReq      = core.AnalyzeEmotionReq
	AnalyzeEmotionResp     = core.AnalyzeEmotionResp
	ChatReq                = core.ChatReq
	ChatResp               = core.ChatResp
	ClassifyMessageReq     = core.ClassifyMessageReq
	ClassifyMessageResp    = core.ClassifyMessageResp
	ContentModerationReq   = core.ContentModerationReq
	ContentModerationResp  = core.ContentModerationResp
	CreateTemplateReq      = core.CreateTemplateReq
	CreateTemplateResp     = core.CreateTemplateResp
	DeleteTemplateReq      = core.DeleteTemplateReq
	DeleteTemplateResp     = core.DeleteTemplateResp
	DetectIntentReq        = core.DetectIntentReq
	DetectIntentResp       = core.DetectIntentResp
	DetectRiskReq          = core.DetectRiskReq
	DetectRiskResp         = core.DetectRiskResp
	ExtractSlotsReq        = core.ExtractSlotsReq
	ExtractSlotsResp       = core.ExtractSlotsResp
	GetRoutingStrategyReq  = core.GetRoutingStrategyReq
	GetRoutingStrategyResp = core.GetRoutingStrategyResp
	GetTemplateReq         = core.GetTemplateReq
	GetTemplateResp        = core.GetTemplateResp
	ListTemplatesReq       = core.ListTemplatesReq
	ListTemplatesResp      = core.ListTemplatesResp
	RenderTemplateReq      = core.RenderTemplateReq
	RenderTemplateResp     = core.RenderTemplateResp
	RouteReq               = core.RouteReq
	RouteResp              = core.RouteResp
	SearchReq              = core.SearchReq
	SearchResp             = core.SearchResp
	TransferToHumanReq     = core.TransferToHumanReq
	TransferToHumanResp    = core.TransferToHumanResp
	UpdateTemplateReq      = core.UpdateTemplateReq
	UpdateTemplateResp     = core.UpdateTemplateResp

	PromptService interface {
		// 获取单个模板
		GetTemplate(ctx context.Context, in *GetTemplateReq, opts ...grpc.CallOption) (*GetTemplateResp, error)
		// 获取模板列表
		ListTemplates(ctx context.Context, in *ListTemplatesReq, opts ...grpc.CallOption) (*ListTemplatesResp, error)
		// 创建模板
		CreateTemplate(ctx context.Context, in *CreateTemplateReq, opts ...grpc.CallOption) (*CreateTemplateResp, error)
		// 更新模板
		UpdateTemplate(ctx context.Context, in *UpdateTemplateReq, opts ...grpc.CallOption) (*UpdateTemplateResp, error)
		// 删除模板
		DeleteTemplate(ctx context.Context, in *DeleteTemplateReq, opts ...grpc.CallOption) (*DeleteTemplateResp, error)
		// 渲染模板（填充变量）
		RenderTemplate(ctx context.Context, in *RenderTemplateReq, opts ...grpc.CallOption) (*RenderTemplateResp, error)
	}

	defaultPromptService struct {
		cli zrpc.Client
	}
)

func NewPromptService(cli zrpc.Client) PromptService {
	return &defaultPromptService{
		cli: cli,
	}
}

// 获取单个模板
func (m *defaultPromptService) GetTemplate(ctx context.Context, in *GetTemplateReq, opts ...grpc.CallOption) (*GetTemplateResp, error) {
	client := core.NewPromptServiceClient(m.cli.Conn())
	return client.GetTemplate(ctx, in, opts...)
}

// 获取模板列表
func (m *defaultPromptService) ListTemplates(ctx context.Context, in *ListTemplatesReq, opts ...grpc.CallOption) (*ListTemplatesResp, error) {
	client := core.NewPromptServiceClient(m.cli.Conn())
	return client.ListTemplates(ctx, in, opts...)
}

// 创建模板
func (m *defaultPromptService) CreateTemplate(ctx context.Context, in *CreateTemplateReq, opts ...grpc.CallOption) (*CreateTemplateResp, error) {
	client := core.NewPromptServiceClient(m.cli.Conn())
	return client.CreateTemplate(ctx, in, opts...)
}

// 更新模板
func (m *defaultPromptService) UpdateTemplate(ctx context.Context, in *UpdateTemplateReq, opts ...grpc.CallOption) (*UpdateTemplateResp, error) {
	client := core.NewPromptServiceClient(m.cli.Conn())
	return client.UpdateTemplate(ctx, in, opts...)
}

// 删除模板
func (m *defaultPromptService) DeleteTemplate(ctx context.Context, in *DeleteTemplateReq, opts ...grpc.CallOption) (*DeleteTemplateResp, error) {
	client := core.NewPromptServiceClient(m.cli.Conn())
	return client.DeleteTemplate(ctx, in, opts...)
}

// 渲染模板（填充变量）
func (m *defaultPromptService) RenderTemplate(ctx context.Context, in *RenderTemplateReq, opts ...grpc.CallOption) (*RenderTemplateResp, error) {
	client := core.NewPromptServiceClient(m.cli.Conn())
	return client.RenderTemplate(ctx, in, opts...)
}
