// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: core.proto

package emotionservice

import (
	"context"

	"core-service/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalyzeEmotionReq      = core.AnalyzeEmotionReq
	AnalyzeEmotionResp     = core.AnalyzeEmotionResp
	ChatReq                = core.ChatReq
	ChatResp               = core.ChatResp
	ClassifyMessageReq     = core.ClassifyMessageReq
	ClassifyMessageResp    = core.ClassifyMessageResp
	ContentModerationReq   = core.ContentModerationReq
	ContentModerationResp  = core.ContentModerationResp
	CreateTemplateReq      = core.CreateTemplateReq
	CreateTemplateResp     = core.CreateTemplateResp
	DeleteTemplateReq      = core.DeleteTemplateReq
	DeleteTemplateResp     = core.DeleteTemplateResp
	DetectIntentReq        = core.DetectIntentReq
	DetectIntentResp       = core.DetectIntentResp
	DetectRiskReq          = core.DetectRiskReq
	DetectRiskResp         = core.DetectRiskResp
	ExtractSlotsReq        = core.ExtractSlotsReq
	ExtractSlotsResp       = core.ExtractSlotsResp
	GetRoutingStrategyReq  = core.GetRoutingStrategyReq
	GetRoutingStrategyResp = core.GetRoutingStrategyResp
	GetTemplateReq         = core.GetTemplateReq
	GetTemplateResp        = core.GetTemplateResp
	ListTemplatesReq       = core.ListTemplatesReq
	ListTemplatesResp      = core.ListTemplatesResp
	RenderTemplateReq      = core.RenderTemplateReq
	RenderTemplateResp     = core.RenderTemplateResp
	RouteReq               = core.RouteReq
	RouteResp              = core.RouteResp
	SearchReq              = core.SearchReq
	SearchResp             = core.SearchResp
	TransferToHumanReq     = core.TransferToHumanReq
	TransferToHumanResp    = core.TransferToHumanResp
	UpdateTemplateReq      = core.UpdateTemplateReq
	UpdateTemplateResp     = core.UpdateTemplateResp

	EmotionService interface {
		// 分析用户情绪
		AnalyzeEmotion(ctx context.Context, in *AnalyzeEmotionReq, opts ...grpc.CallOption) (*AnalyzeEmotionResp, error)
		// 风险预警检测（检测高危用户）
		DetectRisk(ctx context.Context, in *DetectRiskReq, opts ...grpc.CallOption) (*DetectRiskResp, error)
		// 内容合规审核（支持双向审核：用户输入 + AI输出）
		ContentModeration(ctx context.Context, in *ContentModerationReq, opts ...grpc.CallOption) (*ContentModerationResp, error)
	}

	defaultEmotionService struct {
		cli zrpc.Client
	}
)

func NewEmotionService(cli zrpc.Client) EmotionService {
	return &defaultEmotionService{
		cli: cli,
	}
}

// 分析用户情绪
func (m *defaultEmotionService) AnalyzeEmotion(ctx context.Context, in *AnalyzeEmotionReq, opts ...grpc.CallOption) (*AnalyzeEmotionResp, error) {
	client := core.NewEmotionServiceClient(m.cli.Conn())
	return client.AnalyzeEmotion(ctx, in, opts...)
}

// 风险预警检测（检测高危用户）
func (m *defaultEmotionService) DetectRisk(ctx context.Context, in *DetectRiskReq, opts ...grpc.CallOption) (*DetectRiskResp, error) {
	client := core.NewEmotionServiceClient(m.cli.Conn())
	return client.DetectRisk(ctx, in, opts...)
}

// 内容合规审核（支持双向审核：用户输入 + AI输出）
func (m *defaultEmotionService) ContentModeration(ctx context.Context, in *ContentModerationReq, opts ...grpc.CallOption) (*ContentModerationResp, error) {
	client := core.NewEmotionServiceClient(m.cli.Conn())
	return client.ContentModeration(ctx, in, opts...)
}
