// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: core.proto

package intentservice

import (
	"context"

	"core-service/core"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalyzeEmotionReq      = core.AnalyzeEmotionReq
	AnalyzeEmotionResp     = core.AnalyzeEmotionResp
	ChatReq                = core.ChatReq
	ChatResp               = core.ChatResp
	ClassifyMessageReq     = core.ClassifyMessageReq
	ClassifyMessageResp    = core.ClassifyMessageResp
	ContentModerationReq   = core.ContentModerationReq
	ContentModerationResp  = core.ContentModerationResp
	CreateTemplateReq      = core.CreateTemplateReq
	CreateTemplateResp     = core.CreateTemplateResp
	DeleteTemplateReq      = core.DeleteTemplateReq
	DeleteTemplateResp     = core.DeleteTemplateResp
	DetectIntentReq        = core.DetectIntentReq
	DetectIntentResp       = core.DetectIntentResp
	DetectRiskReq          = core.DetectRiskReq
	DetectRiskResp         = core.DetectRiskResp
	ExtractSlotsReq        = core.ExtractSlotsReq
	ExtractSlotsResp       = core.ExtractSlotsResp
	GetRoutingStrategyReq  = core.GetRoutingStrategyReq
	GetRoutingStrategyResp = core.GetRoutingStrategyResp
	GetTemplateReq         = core.GetTemplateReq
	GetTemplateResp        = core.GetTemplateResp
	ListTemplatesReq       = core.ListTemplatesReq
	ListTemplatesResp      = core.ListTemplatesResp
	RenderTemplateReq      = core.RenderTemplateReq
	RenderTemplateResp     = core.RenderTemplateResp
	RouteReq               = core.RouteReq
	RouteResp              = core.RouteResp
	SearchReq              = core.SearchReq
	SearchResp             = core.SearchResp
	TransferToHumanReq     = core.TransferToHumanReq
	TransferToHumanResp    = core.TransferToHumanResp
	UpdateTemplateReq      = core.UpdateTemplateReq
	UpdateTemplateResp     = core.UpdateTemplateResp

	IntentService interface {
		// 识别用户意图
		DetectIntent(ctx context.Context, in *DetectIntentReq, opts ...grpc.CallOption) (*DetectIntentResp, error)
		// 消息分类（快速分类：咨询/投诉/闲聊等）
		ClassifyMessage(ctx context.Context, in *ClassifyMessageReq, opts ...grpc.CallOption) (*ClassifyMessageResp, error)
		// 提取槽位信息（NER）
		ExtractSlots(ctx context.Context, in *ExtractSlotsReq, opts ...grpc.CallOption) (*ExtractSlotsResp, error)
	}

	defaultIntentService struct {
		cli zrpc.Client
	}
)

func NewIntentService(cli zrpc.Client) IntentService {
	return &defaultIntentService{
		cli: cli,
	}
}

// 识别用户意图
func (m *defaultIntentService) DetectIntent(ctx context.Context, in *DetectIntentReq, opts ...grpc.CallOption) (*DetectIntentResp, error) {
	client := core.NewIntentServiceClient(m.cli.Conn())
	return client.DetectIntent(ctx, in, opts...)
}

// 消息分类（快速分类：咨询/投诉/闲聊等）
func (m *defaultIntentService) ClassifyMessage(ctx context.Context, in *ClassifyMessageReq, opts ...grpc.CallOption) (*ClassifyMessageResp, error) {
	client := core.NewIntentServiceClient(m.cli.Conn())
	return client.ClassifyMessage(ctx, in, opts...)
}

// 提取槽位信息（NER）
func (m *defaultIntentService) ExtractSlots(ctx context.Context, in *ExtractSlotsReq, opts ...grpc.CallOption) (*ExtractSlotsResp, error) {
	client := core.NewIntentServiceClient(m.cli.Conn())
	return client.ExtractSlots(ctx, in, opts...)
}
