// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: core.proto

package server

import (
	"context"

	"core-service/core"
	"core-service/internal/logic/promptservice"
	"core-service/internal/svc"
)

type PromptServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedPromptServiceServer
}

func NewPromptServiceServer(svcCtx *svc.ServiceContext) *PromptServiceServer {
	return &PromptServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取单个模板
func (s *PromptServiceServer) GetTemplate(ctx context.Context, in *core.GetTemplateReq) (*core.GetTemplateResp, error) {
	l := promptservicelogic.NewGetTemplateLogic(ctx, s.svcCtx)
	return l.GetTemplate(in)
}

// 获取模板列表
func (s *PromptServiceServer) ListTemplates(ctx context.Context, in *core.ListTemplatesReq) (*core.ListTemplatesResp, error) {
	l := promptservicelogic.NewListTemplatesLogic(ctx, s.svcCtx)
	return l.ListTemplates(in)
}

// 创建模板
func (s *PromptServiceServer) CreateTemplate(ctx context.Context, in *core.CreateTemplateReq) (*core.CreateTemplateResp, error) {
	l := promptservicelogic.NewCreateTemplateLogic(ctx, s.svcCtx)
	return l.CreateTemplate(in)
}

// 更新模板
func (s *PromptServiceServer) UpdateTemplate(ctx context.Context, in *core.UpdateTemplateReq) (*core.UpdateTemplateResp, error) {
	l := promptservicelogic.NewUpdateTemplateLogic(ctx, s.svcCtx)
	return l.UpdateTemplate(in)
}

// 删除模板
func (s *PromptServiceServer) DeleteTemplate(ctx context.Context, in *core.DeleteTemplateReq) (*core.DeleteTemplateResp, error) {
	l := promptservicelogic.NewDeleteTemplateLogic(ctx, s.svcCtx)
	return l.DeleteTemplate(in)
}

// 渲染模板（填充变量）
func (s *PromptServiceServer) RenderTemplate(ctx context.Context, in *core.RenderTemplateReq) (*core.RenderTemplateResp, error) {
	l := promptservicelogic.NewRenderTemplateLogic(ctx, s.svcCtx)
	return l.RenderTemplate(in)
}
