// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: core.proto

package server

import (
	"context"

	"core-service/core"
	"core-service/internal/logic/intentservice"
	"core-service/internal/svc"
)

type IntentServiceServer struct {
	svcCtx *svc.ServiceContext
	core.UnimplementedIntentServiceServer
}

func NewIntentServiceServer(svcCtx *svc.ServiceContext) *IntentServiceServer {
	return &IntentServiceServer{
		svcCtx: svcCtx,
	}
}

// 识别用户意图
func (s *IntentServiceServer) DetectIntent(ctx context.Context, in *core.DetectIntentReq) (*core.DetectIntentResp, error) {
	l := intentservicelogic.NewDetectIntentLogic(ctx, s.svcCtx)
	return l.DetectIntent(in)
}

// 消息分类（快速分类：咨询/投诉/闲聊等）
func (s *IntentServiceServer) ClassifyMessage(ctx context.Context, in *core.ClassifyMessageReq) (*core.ClassifyMessageResp, error) {
	l := intentservicelogic.NewClassifyMessageLogic(ctx, s.svcCtx)
	return l.ClassifyMessage(in)
}

// 提取槽位信息（NER）
func (s *IntentServiceServer) ExtractSlots(ctx context.Context, in *core.ExtractSlotsReq) (*core.ExtractSlotsResp, error) {
	l := intentservicelogic.NewExtractSlotsLogic(ctx, s.svcCtx)
	return l.ExtractSlots(in)
}
