// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: data.proto

package server

import (
	"context"

	"data-service/data"
	"data-service/internal/logic/knowledgeservice"
	"data-service/internal/svc"
)

type KnowledgeServiceServer struct {
	svcCtx *svc.ServiceContext
	data.UnimplementedKnowledgeServiceServer
}

func NewKnowledgeServiceServer(svcCtx *svc.ServiceContext) *KnowledgeServiceServer {
	return &KnowledgeServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *KnowledgeServiceServer) CreateKnowledgeBase(ctx context.Context, in *data.CreateKnowledgeBaseReq) (*data.CreateKnowledgeBaseResp, error) {
	l := knowledgeservicelogic.NewCreateKnowledgeBaseLogic(ctx, s.svcCtx)
	return l.CreateKnowledgeBase(in)
}

func (s *KnowledgeServiceServer) ListKnowledgeBases(ctx context.Context, in *data.ListKnowledgeBasesReq) (*data.ListKnowledgeBasesResp, error) {
	l := knowledgeservicelogic.NewListKnowledgeBasesLogic(ctx, s.svcCtx)
	return l.ListKnowledgeBases(in)
}

func (s *KnowledgeServiceServer) GetKnowledgeBase(ctx context.Context, in *data.GetKnowledgeBaseReq) (*data.GetKnowledgeBaseResp, error) {
	l := knowledgeservicelogic.NewGetKnowledgeBaseLogic(ctx, s.svcCtx)
	return l.GetKnowledgeBase(in)
}

func (s *KnowledgeServiceServer) DeleteKnowledgeBase(ctx context.Context, in *data.DeleteKnowledgeBaseReq) (*data.DeleteKnowledgeBaseResp, error) {
	l := knowledgeservicelogic.NewDeleteKnowledgeBaseLogic(ctx, s.svcCtx)
	return l.DeleteKnowledgeBase(in)
}
